# Generated by Django 4.2.5 on 2023-09-07 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('bn_id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='banner_images')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('br_id', models.IntegerField(primary_key=True, serialize=False)),
                ('br_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(choices=[(True, 'is_active'), (False, 'inactive')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ct_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ct_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(choices=[(True, 'is_active'), (False, 'inactive')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
                ('status', models.BooleanField(choices=[(True, 'is_active'), (False, 'inactive')], default=True)),
                ('session', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pr_name', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('images', models.ImageField(upload_to='product_images')),
                ('status', models.BooleanField(choices=[(True, 'is_active'), (False, 'inactive')], default=True)),
                ('br_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
                ('ct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
