# Generated by Django 4.2.5 on 2023-09-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customers_password_alter_customers_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
