# Generated by Django 4.2.5 on 2023-09-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customers_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'pending')], default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'pending')], default=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'pending')], default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'pending')], default=True),
        ),
    ]
