# Generated by Django 4.2.5 on 2023-09-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customers_otp_alter_brand_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=True),
        ),
    ]
