# Generated by Django 4.2.5 on 2023-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customers_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='otp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
