# Generated by Django 4.2.5 on 2023-09-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_customers_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
