# Generated by Django 4.2.5 on 2023-09-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_customers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ct_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
